<?php

namespace Proxies\__CG__\FraisBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Fichefrais extends \FraisBundle\Entity\Fichefrais implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'FraisBundle\\Entity\\Fichefrais' . "\0" . 'id', '' . "\0" . 'FraisBundle\\Entity\\Fichefrais' . "\0" . 'date', '' . "\0" . 'FraisBundle\\Entity\\Fichefrais' . "\0" . 'nbjustificatifs', '' . "\0" . 'FraisBundle\\Entity\\Fichefrais' . "\0" . 'montantvalide', '' . "\0" . 'FraisBundle\\Entity\\Fichefrais' . "\0" . 'datemodif', '' . "\0" . 'FraisBundle\\Entity\\Fichefrais' . "\0" . 'idEtat', '' . "\0" . 'FraisBundle\\Entity\\Fichefrais' . "\0" . 'idvisiteur');
        }

        return array('__isInitialized__', '' . "\0" . 'FraisBundle\\Entity\\Fichefrais' . "\0" . 'id', '' . "\0" . 'FraisBundle\\Entity\\Fichefrais' . "\0" . 'date', '' . "\0" . 'FraisBundle\\Entity\\Fichefrais' . "\0" . 'nbjustificatifs', '' . "\0" . 'FraisBundle\\Entity\\Fichefrais' . "\0" . 'montantvalide', '' . "\0" . 'FraisBundle\\Entity\\Fichefrais' . "\0" . 'datemodif', '' . "\0" . 'FraisBundle\\Entity\\Fichefrais' . "\0" . 'idEtat', '' . "\0" . 'FraisBundle\\Entity\\Fichefrais' . "\0" . 'idvisiteur');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Fichefrais $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbjustificatifs($nbjustificatifs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbjustificatifs', array($nbjustificatifs));

        return parent::setNbjustificatifs($nbjustificatifs);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbjustificatifs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbjustificatifs', array());

        return parent::getNbjustificatifs();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantvalide($montantvalide)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantvalide', array($montantvalide));

        return parent::setMontantvalide($montantvalide);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantvalide()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantvalide', array());

        return parent::getMontantvalide();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatemodif($datemodif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatemodif', array($datemodif));

        return parent::setDatemodif($datemodif);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatemodif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatemodif', array());

        return parent::getDatemodif();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEtat(\FraisBundle\Entity\Etat $idEtat = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEtat', array($idEtat));

        return parent::setIdEtat($idEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEtat', array());

        return parent::getIdEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdvisiteur(\FraisBundle\Entity\Visiteur $idvisiteur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdvisiteur', array($idvisiteur));

        return parent::setIdvisiteur($idvisiteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdvisiteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdvisiteur', array());

        return parent::getIdvisiteur();
    }

}
