frais_homepage:
    path:     /home/
    defaults: { _controller: FraisBundle:Default:index }
   
frais_connexionV:
    path:     /connexionV/
    defaults: { _controller: FraisBundle:Default:formV }

deconnexion:
    path:     /deconnexion/
    defaults: { _controller: FraisBundle:Default:deconnexion }
    
frais_connexionC:
    path:     /connexionC/
    defaults: { _controller: FraisBundle:Default:formC }
    
#frais_consulterV :
#    path: /consulterfichefrais/
#    defaults: {_controller: FraisBundle:Visiteur:consulterFrais}

    
consulter:
    path:     /consulter/
    defaults: { _controller: FraisBundle:Default:getMoisV }   
    
renseignerHF:
    path:     /renseignerHF/
    defaults: { _controller: FraisBundle:Default:renseignerHF }
    
renseignerHome:
    path:     /renseignerHome/
    defaults: { _controller: FraisBundle:Default:renseignerHome }
    
modifierFF:
    path:     /modifierFF/
    defaults: { _controller: FraisBundle:Default:modifierFF }
    
modifierFiche:
    path:     /modifierFiche/
    defaults: { _controller: FraisBundle:Default:modifierFiche }
    
supprimerHF:
    path:     /supprimerHF/
    defaults: { _controller: FraisBundle:Default:supprimerHF }

suivreFiche:
    path:     /suivreFiche/
    defaults: { _controller: FraisBundle:Default:suivreFiche }
    
validerFiche:
    path:     /validerFiche/
    defaults: { _controller: FraisBundle:Default:validerFiche }
    
detailFiche:
    path:     /detailFiche/
    defaults: { _controller: FraisBundle:Default:detailFiche }
    
misePaiement:
    path:     /misePaiement/
    defaults: { _controller: FraisBundle:Default:misePaiement }


    
    
