<?php

namespace FraisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FraishorsforfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraishorsforfaitRepository extends EntityRepository
{
    public function getConsulter($idVisiteur, $date ) {
        
        
        //FicheFrais.dateModif
        //LigneFraisHorsForfait.date/montant/libelle
        //LigneFraisForfait.quantite
        //FraisForfait.libelle
 
        
//        $queryBuilder = $this->_em->createQueryBuilder()->select('f')->from($this->_entityName, 'f');
//        $queryBuilder->where('f.id= :id')->setParameter('id' , $idVisiteur)
//                ->andWhere('f.mois = :mois')->setParameter('mois', $mois) ;
//        $query = $this->_em->createQueryBuilder->select($this->_entityName,'l')->join('l.id', 'c')->addSelect('l');
//        $result = $query->getQuery()->getResult();
//        $query = $this->_em->createQueryBuilder()->select('Lignefraishorsforfait')->from($this->_entityName, 'Lignefraishorsforfait')
//                ->innerjoin('Lignefraishorsforfait.libelle', 'Contenir', Join::ON, 'Lignefraishorsforfait.id = Contenir.id_LigneFraisHorsForfait');
//        $result = $query->getQuery()->getResult();
//        $query = $this->createQueryBuilder('l')
//                ->join('l.libelle', 'li')
//                ->join('l.montant', 'm')
//                ->addSelect('li')
//                ->addSelect('m');
//        $result = $query->getQuery()->getResult();


//        $query = $this->_em->createQuery("SELECT l , c FROM FraisBundle\Entity\Lignefraishorsforfait l JOIN l.Contenir c WHERE c.id = 'f4' AND c.mois = '01' ");
////                ->setParameter('idVisiteur', $idVisiteur)
////                ->setParameter('mois', $mois);
//        $result = $query->getResult();
        
        //"SELECT a FROM SdzBlogBundle:Article a JOIN SdzBlogBundle:Commentaire c WHERE a.id=c.article"

//        $query = $this->_em->createQuery("SELECT l, c "
//                . "FROM FraisBundle:Lignefraishorsforfait l "
//                . "JOIN FraisBundle:Contenir c "
//                . "WHERE c.id = :idVisiteur AND c.mois = :mois ")
//                ->setParameter('idVisiteur', $idVisiteur)
//                ->setParameter('mois', $mois);
//        $result = $query->getResult();
        
        $queryBuilder = $this->_em->createQueryBuilder()->select('l')->from($this->_entityName, 'l')->join('FraisBundle:Contenir', 'c');
        $queryBuilder->where('c.id = :idVisiteur')->setParameter('idVisiteur' , $idVisiteur)
                ->andWhere('c.date = :date')->setParameter('date', $date);
                
        
        $result = $queryBuilder->getQuery()->getResult()  ;
        
        

        if (count($result) > 0){           
            return $result ;
        } else {
            return false ;
        }
    }
    
    
     public function deleteFraisHF($id) {

        
        $queryBuilder = $this->_em->createQueryBuilder()->delete()->from($this->_entityName, 'l');
        $queryBuilder->where('l.id = :id')->setParameter('id' , $id);
                
                
         $result = $queryBuilder->getQuery()->execute() ;
        
        

        if (count($result) > 0){           
            return $result ;
        } else {
            return false ;
        }
    }
}
