<?php

namespace FraisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FraisforfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraisforfaitRepository extends EntityRepository
{
     public function getFraisForfait($idVisiteur, $dateSQL) {

        
        $queryBuilder = $this->_em->createQueryBuilder()->select('f')->from($this->_entityName, 'f')->join('FraisBundle:Lignefraisforfait', 'l');
        $queryBuilder->where('l.id = :idVisiteur')->setParameter('idVisiteur' , $idVisiteur)
                
                 ->andWhere('l.date = :date')->setParameter('date', $dateSQL) ;
        
        $lesFrais = $queryBuilder->getQuery()->getResult()  ;
        
        foreach($lesFrais as $unFrais){
            $result = $unFrais ;
        }
        

        if (count($lesFrais) > 0){           
            return $lesFrais ;
        } else {
            return false ;
        }
    }
}
