<?php

namespace FraisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VisiteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteurRepository extends EntityRepository
{
    
     public function connexionVisiteur($login, $mdp) {
        $queryBuilder = $this->_em->createQueryBuilder()->select('v')->from($this->_entityName, 'v');
        $queryBuilder->where('v.login= :login')->setParameter('login', $login)
                ->andWhere('v.mdp = :mdp')->setParameter('mdp', $mdp);

        $lesVisiteurs = $queryBuilder->getQuery()->getResult();

        foreach($lesVisiteurs as $unVisiteur){
            $return = $unVisiteur ;
        }
        if ($return != null) {
            return $return;
        } else {
            return false;
        }
    }
}
